// Code generated by go-swagger; DO NOT EDIT.

package provisioning

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grafana/grafana-openapi-client-go/models"
)

// RouteExportMuteTimingReader is a Reader for the RouteExportMuteTiming structure.
type RouteExportMuteTimingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RouteExportMuteTimingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRouteExportMuteTimingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewRouteExportMuteTimingForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/provisioning/mute-timings/{name}/export] RouteExportMuteTiming", response, response.Code())
	}
}

// NewRouteExportMuteTimingOK creates a RouteExportMuteTimingOK with default headers values
func NewRouteExportMuteTimingOK() *RouteExportMuteTimingOK {
	return &RouteExportMuteTimingOK{}
}

/*
RouteExportMuteTimingOK describes a response with status code 200, with default header values.

AlertingFileExport
*/
type RouteExportMuteTimingOK struct {
	Payload *models.AlertingFileExport
}

// IsSuccess returns true when this route export mute timing Ok response has a 2xx status code
func (o *RouteExportMuteTimingOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this route export mute timing Ok response has a 3xx status code
func (o *RouteExportMuteTimingOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this route export mute timing Ok response has a 4xx status code
func (o *RouteExportMuteTimingOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this route export mute timing Ok response has a 5xx status code
func (o *RouteExportMuteTimingOK) IsServerError() bool {
	return false
}

// IsCode returns true when this route export mute timing Ok response a status code equal to that given
func (o *RouteExportMuteTimingOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the route export mute timing Ok response
func (o *RouteExportMuteTimingOK) Code() int {
	return 200
}

func (o *RouteExportMuteTimingOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/provisioning/mute-timings/{name}/export][%d] routeExportMuteTimingOk %s", 200, payload)
}

func (o *RouteExportMuteTimingOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/provisioning/mute-timings/{name}/export][%d] routeExportMuteTimingOk %s", 200, payload)
}

func (o *RouteExportMuteTimingOK) GetPayload() *models.AlertingFileExport {
	return o.Payload
}

func (o *RouteExportMuteTimingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AlertingFileExport)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRouteExportMuteTimingForbidden creates a RouteExportMuteTimingForbidden with default headers values
func NewRouteExportMuteTimingForbidden() *RouteExportMuteTimingForbidden {
	return &RouteExportMuteTimingForbidden{}
}

/*
RouteExportMuteTimingForbidden describes a response with status code 403, with default header values.

PermissionDenied
*/
type RouteExportMuteTimingForbidden struct {
	Payload models.PermissionDenied
}

// IsSuccess returns true when this route export mute timing forbidden response has a 2xx status code
func (o *RouteExportMuteTimingForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this route export mute timing forbidden response has a 3xx status code
func (o *RouteExportMuteTimingForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this route export mute timing forbidden response has a 4xx status code
func (o *RouteExportMuteTimingForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this route export mute timing forbidden response has a 5xx status code
func (o *RouteExportMuteTimingForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this route export mute timing forbidden response a status code equal to that given
func (o *RouteExportMuteTimingForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the route export mute timing forbidden response
func (o *RouteExportMuteTimingForbidden) Code() int {
	return 403
}

func (o *RouteExportMuteTimingForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/provisioning/mute-timings/{name}/export][%d] routeExportMuteTimingForbidden %s", 403, payload)
}

func (o *RouteExportMuteTimingForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/provisioning/mute-timings/{name}/export][%d] routeExportMuteTimingForbidden %s", 403, payload)
}

func (o *RouteExportMuteTimingForbidden) GetPayload() models.PermissionDenied {
	return o.Payload
}

func (o *RouteExportMuteTimingForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
