// Code generated by go-swagger; DO NOT EDIT.

package provisioning

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewRouteExportMuteTimingsParams creates a new RouteExportMuteTimingsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRouteExportMuteTimingsParams() *RouteExportMuteTimingsParams {
	return &RouteExportMuteTimingsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRouteExportMuteTimingsParamsWithTimeout creates a new RouteExportMuteTimingsParams object
// with the ability to set a timeout on a request.
func NewRouteExportMuteTimingsParamsWithTimeout(timeout time.Duration) *RouteExportMuteTimingsParams {
	return &RouteExportMuteTimingsParams{
		timeout: timeout,
	}
}

// NewRouteExportMuteTimingsParamsWithContext creates a new RouteExportMuteTimingsParams object
// with the ability to set a context for a request.
func NewRouteExportMuteTimingsParamsWithContext(ctx context.Context) *RouteExportMuteTimingsParams {
	return &RouteExportMuteTimingsParams{
		Context: ctx,
	}
}

// NewRouteExportMuteTimingsParamsWithHTTPClient creates a new RouteExportMuteTimingsParams object
// with the ability to set a custom HTTPClient for a request.
func NewRouteExportMuteTimingsParamsWithHTTPClient(client *http.Client) *RouteExportMuteTimingsParams {
	return &RouteExportMuteTimingsParams{
		HTTPClient: client,
	}
}

/*
RouteExportMuteTimingsParams contains all the parameters to send to the API endpoint

	for the route export mute timings operation.

	Typically these are written to a http.Request.
*/
type RouteExportMuteTimingsParams struct {

	/* Download.

	   Whether to initiate a download of the file or not.
	*/
	Download *bool

	/* Format.

	   Format of the downloaded file, either yaml or json. Accept header can also be used, but the query parameter will take precedence.

	   Default: "yaml"
	*/
	Format *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the route export mute timings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RouteExportMuteTimingsParams) WithDefaults() *RouteExportMuteTimingsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the route export mute timings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RouteExportMuteTimingsParams) SetDefaults() {
	var (
		downloadDefault = bool(false)

		formatDefault = string("yaml")
	)

	val := RouteExportMuteTimingsParams{
		Download: &downloadDefault,
		Format:   &formatDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the route export mute timings params
func (o *RouteExportMuteTimingsParams) WithTimeout(timeout time.Duration) *RouteExportMuteTimingsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the route export mute timings params
func (o *RouteExportMuteTimingsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the route export mute timings params
func (o *RouteExportMuteTimingsParams) WithContext(ctx context.Context) *RouteExportMuteTimingsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the route export mute timings params
func (o *RouteExportMuteTimingsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the route export mute timings params
func (o *RouteExportMuteTimingsParams) WithHTTPClient(client *http.Client) *RouteExportMuteTimingsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the route export mute timings params
func (o *RouteExportMuteTimingsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDownload adds the download to the route export mute timings params
func (o *RouteExportMuteTimingsParams) WithDownload(download *bool) *RouteExportMuteTimingsParams {
	o.SetDownload(download)
	return o
}

// SetDownload adds the download to the route export mute timings params
func (o *RouteExportMuteTimingsParams) SetDownload(download *bool) {
	o.Download = download
}

// WithFormat adds the format to the route export mute timings params
func (o *RouteExportMuteTimingsParams) WithFormat(format *string) *RouteExportMuteTimingsParams {
	o.SetFormat(format)
	return o
}

// SetFormat adds the format to the route export mute timings params
func (o *RouteExportMuteTimingsParams) SetFormat(format *string) {
	o.Format = format
}

// WriteToRequest writes these params to a swagger request
func (o *RouteExportMuteTimingsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Download != nil {

		// query param download
		var qrDownload bool

		if o.Download != nil {
			qrDownload = *o.Download
		}
		qDownload := swag.FormatBool(qrDownload)
		if qDownload != "" {

			if err := r.SetQueryParam("download", qDownload); err != nil {
				return err
			}
		}
	}

	if o.Format != nil {

		// query param format
		var qrFormat string

		if o.Format != nil {
			qrFormat = *o.Format
		}
		qFormat := qrFormat
		if qFormat != "" {

			if err := r.SetQueryParam("format", qFormat); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
