// Code generated by go-swagger; DO NOT EDIT.

package provisioning

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grafana/grafana-openapi-client-go/models"
)

// RouteExportMuteTimingsReader is a Reader for the RouteExportMuteTimings structure.
type RouteExportMuteTimingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RouteExportMuteTimingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRouteExportMuteTimingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewRouteExportMuteTimingsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/provisioning/mute-timings/export] RouteExportMuteTimings", response, response.Code())
	}
}

// NewRouteExportMuteTimingsOK creates a RouteExportMuteTimingsOK with default headers values
func NewRouteExportMuteTimingsOK() *RouteExportMuteTimingsOK {
	return &RouteExportMuteTimingsOK{}
}

/*
RouteExportMuteTimingsOK describes a response with status code 200, with default header values.

AlertingFileExport
*/
type RouteExportMuteTimingsOK struct {
	Payload *models.AlertingFileExport
}

// IsSuccess returns true when this route export mute timings Ok response has a 2xx status code
func (o *RouteExportMuteTimingsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this route export mute timings Ok response has a 3xx status code
func (o *RouteExportMuteTimingsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this route export mute timings Ok response has a 4xx status code
func (o *RouteExportMuteTimingsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this route export mute timings Ok response has a 5xx status code
func (o *RouteExportMuteTimingsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this route export mute timings Ok response a status code equal to that given
func (o *RouteExportMuteTimingsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the route export mute timings Ok response
func (o *RouteExportMuteTimingsOK) Code() int {
	return 200
}

func (o *RouteExportMuteTimingsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/provisioning/mute-timings/export][%d] routeExportMuteTimingsOk %s", 200, payload)
}

func (o *RouteExportMuteTimingsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/provisioning/mute-timings/export][%d] routeExportMuteTimingsOk %s", 200, payload)
}

func (o *RouteExportMuteTimingsOK) GetPayload() *models.AlertingFileExport {
	return o.Payload
}

func (o *RouteExportMuteTimingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AlertingFileExport)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRouteExportMuteTimingsForbidden creates a RouteExportMuteTimingsForbidden with default headers values
func NewRouteExportMuteTimingsForbidden() *RouteExportMuteTimingsForbidden {
	return &RouteExportMuteTimingsForbidden{}
}

/*
RouteExportMuteTimingsForbidden describes a response with status code 403, with default header values.

PermissionDenied
*/
type RouteExportMuteTimingsForbidden struct {
	Payload models.PermissionDenied
}

// IsSuccess returns true when this route export mute timings forbidden response has a 2xx status code
func (o *RouteExportMuteTimingsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this route export mute timings forbidden response has a 3xx status code
func (o *RouteExportMuteTimingsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this route export mute timings forbidden response has a 4xx status code
func (o *RouteExportMuteTimingsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this route export mute timings forbidden response has a 5xx status code
func (o *RouteExportMuteTimingsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this route export mute timings forbidden response a status code equal to that given
func (o *RouteExportMuteTimingsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the route export mute timings forbidden response
func (o *RouteExportMuteTimingsForbidden) Code() int {
	return 403
}

func (o *RouteExportMuteTimingsForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/provisioning/mute-timings/export][%d] routeExportMuteTimingsForbidden %s", 403, payload)
}

func (o *RouteExportMuteTimingsForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/provisioning/mute-timings/export][%d] routeExportMuteTimingsForbidden %s", 403, payload)
}

func (o *RouteExportMuteTimingsForbidden) GetPayload() models.PermissionDenied {
	return o.Payload
}

func (o *RouteExportMuteTimingsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
