// Code generated by go-swagger; DO NOT EDIT.

package provisioning

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// RouteDeleteContactpointsReader is a Reader for the RouteDeleteContactpoints structure.
type RouteDeleteContactpointsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RouteDeleteContactpointsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewRouteDeleteContactpointsAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /v1/provisioning/contact-points/{UID}] RouteDeleteContactpoints", response, response.Code())
	}
}

// NewRouteDeleteContactpointsAccepted creates a RouteDeleteContactpointsAccepted with default headers values
func NewRouteDeleteContactpointsAccepted() *RouteDeleteContactpointsAccepted {
	return &RouteDeleteContactpointsAccepted{}
}

/*
RouteDeleteContactpointsAccepted describes a response with status code 202, with default header values.

	The contact point was deleted successfully.
*/
type RouteDeleteContactpointsAccepted struct {
}

// IsSuccess returns true when this route delete contactpoints accepted response has a 2xx status code
func (o *RouteDeleteContactpointsAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this route delete contactpoints accepted response has a 3xx status code
func (o *RouteDeleteContactpointsAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this route delete contactpoints accepted response has a 4xx status code
func (o *RouteDeleteContactpointsAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this route delete contactpoints accepted response has a 5xx status code
func (o *RouteDeleteContactpointsAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this route delete contactpoints accepted response a status code equal to that given
func (o *RouteDeleteContactpointsAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the route delete contactpoints accepted response
func (o *RouteDeleteContactpointsAccepted) Code() int {
	return 202
}

func (o *RouteDeleteContactpointsAccepted) Error() string {
	return fmt.Sprintf("[DELETE /v1/provisioning/contact-points/{UID}][%d] routeDeleteContactpointsAccepted", 202)
}

func (o *RouteDeleteContactpointsAccepted) String() string {
	return fmt.Sprintf("[DELETE /v1/provisioning/contact-points/{UID}][%d] routeDeleteContactpointsAccepted", 202)
}

func (o *RouteDeleteContactpointsAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
