// Code generated by go-swagger; DO NOT EDIT.

package provisioning

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grafana/grafana-openapi-client-go/models"
)

// RoutePutMuteTimingReader is a Reader for the RoutePutMuteTiming structure.
type RoutePutMuteTimingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RoutePutMuteTimingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewRoutePutMuteTimingAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRoutePutMuteTimingBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /v1/provisioning/mute-timings/{name}] RoutePutMuteTiming", response, response.Code())
	}
}

// NewRoutePutMuteTimingAccepted creates a RoutePutMuteTimingAccepted with default headers values
func NewRoutePutMuteTimingAccepted() *RoutePutMuteTimingAccepted {
	return &RoutePutMuteTimingAccepted{}
}

/*
RoutePutMuteTimingAccepted describes a response with status code 202, with default header values.

MuteTimeInterval
*/
type RoutePutMuteTimingAccepted struct {
	Payload *models.MuteTimeInterval
}

// IsSuccess returns true when this route put mute timing accepted response has a 2xx status code
func (o *RoutePutMuteTimingAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this route put mute timing accepted response has a 3xx status code
func (o *RoutePutMuteTimingAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this route put mute timing accepted response has a 4xx status code
func (o *RoutePutMuteTimingAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this route put mute timing accepted response has a 5xx status code
func (o *RoutePutMuteTimingAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this route put mute timing accepted response a status code equal to that given
func (o *RoutePutMuteTimingAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the route put mute timing accepted response
func (o *RoutePutMuteTimingAccepted) Code() int {
	return 202
}

func (o *RoutePutMuteTimingAccepted) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/provisioning/mute-timings/{name}][%d] routePutMuteTimingAccepted %s", 202, payload)
}

func (o *RoutePutMuteTimingAccepted) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/provisioning/mute-timings/{name}][%d] routePutMuteTimingAccepted %s", 202, payload)
}

func (o *RoutePutMuteTimingAccepted) GetPayload() *models.MuteTimeInterval {
	return o.Payload
}

func (o *RoutePutMuteTimingAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MuteTimeInterval)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRoutePutMuteTimingBadRequest creates a RoutePutMuteTimingBadRequest with default headers values
func NewRoutePutMuteTimingBadRequest() *RoutePutMuteTimingBadRequest {
	return &RoutePutMuteTimingBadRequest{}
}

/*
RoutePutMuteTimingBadRequest describes a response with status code 400, with default header values.

ValidationError
*/
type RoutePutMuteTimingBadRequest struct {
	Payload *models.ValidationError
}

// IsSuccess returns true when this route put mute timing bad request response has a 2xx status code
func (o *RoutePutMuteTimingBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this route put mute timing bad request response has a 3xx status code
func (o *RoutePutMuteTimingBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this route put mute timing bad request response has a 4xx status code
func (o *RoutePutMuteTimingBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this route put mute timing bad request response has a 5xx status code
func (o *RoutePutMuteTimingBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this route put mute timing bad request response a status code equal to that given
func (o *RoutePutMuteTimingBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the route put mute timing bad request response
func (o *RoutePutMuteTimingBadRequest) Code() int {
	return 400
}

func (o *RoutePutMuteTimingBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/provisioning/mute-timings/{name}][%d] routePutMuteTimingBadRequest %s", 400, payload)
}

func (o *RoutePutMuteTimingBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/provisioning/mute-timings/{name}][%d] routePutMuteTimingBadRequest %s", 400, payload)
}

func (o *RoutePutMuteTimingBadRequest) GetPayload() *models.ValidationError {
	return o.Payload
}

func (o *RoutePutMuteTimingBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
