// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DashboardRow dashboard row
//
// swagger:model DashboardRow
type DashboardRow struct {

	// collapse
	Collapse bool `json:"collapse,omitempty"`

	// editable
	Editable bool `json:"editable,omitempty"`

	// height
	Height string `json:"height,omitempty"`

	// panels
	Panels []DashboardPanel `json:"panels"`
}

// Validate validates this dashboard row
func (m *DashboardRow) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dashboard row based on context it is used
func (m *DashboardRow) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DashboardRow) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DashboardRow) UnmarshalBinary(b []byte) error {
	var res DashboardRow
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
