// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// FrameColumn A single column of data in the data frame
//
// swagger:model FrameColumn
type FrameColumn []float32

// Validate validates this frame column
func (m FrameColumn) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this frame column based on context it is used
func (m FrameColumn) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
